# Generated by Django 3.1 on 2020-09-08 22:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechCourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='il',
            new_name='course_type',
        ),
        migrations.RemoveField(
            model_name='details',
            name='sp',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='started_from',
            field=models.DateField(default=datetime.datetime(2020, 9, 8, 22, 28, 22, 839971, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='is_interesting',
            field=models.BooleanField(default=False),
        ),
    ]
