# Generated by Django 3.1 on 2020-09-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TechCourse', '0002_auto_20200908_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='started_from',
            field=models.DateTimeField(verbose_name='Started from'),
        ),
    ]
